### ISSUE TITLE
For two players, the reverse card has no effect

### ISSUE THREAD

**Issue by vanaur** [guilhermebkel/uno-game#17]
Hello, I noticed that, with two players, the "reverse" card has no effect. The expected behavior, I guess, would be to block the other player like the "stop" card.

Maybe the rules of this uno do not define such a behavior, if so, please excuse this unnecessary issue.

**Comment by guilhermebkel** [comment]
Hello @vanaur!

Thanks for reporting it! 😄

In the current rules we consider the reverse card not to work with two players (because with two players the game direction does not matter), but I'll take your suggestion to add in the future a feature to choose which custom rules we want on the game during its creation and one of them will be to add this custom behavior to reverse card with two players ✌️ (https://github.com/guilhermebkel/uno-game/projects/1#card-65181020)
