### ISSUE TITLE
[Feature request] More original UNO features

### ISSUE THREAD

**Issue by DrSkrotum** [guilhermebkel/uno-game#23]
Hello Guilherme, I was asking myself if you planed to add more rules from UNO. I'm mainly thiniking about counter-uno for the person after the one who just hit uno in case of he forgot to tell it, same with +4 contest if he still have the colour he changes. 

Me and my friends like your website very much and I want to congratulate you for all the good work you did on this project !

**Comment by guilhermebkel** [comment]
Hello @DrSkrotum! Thanks a lot for the words :)

Actually I do plan to add more rules (being honest I think it would be good if the player could choose some extra rules during the game cration). I have thought before about the counter-uno, but I haven't done it since I felt like it would not be fair sometimes due to internet delay (in real life actually we have no delay hahah).

Even though I'll add your rule to our [Roadmap](https://github.com/guilhermebkel/uno-game/projects/1) (I think counter-uno is one of the stuffs that make the game really funny and we could really try it out ^^).
